[data]
; DATA_PATH : 데이터 파일 경로
; N_TRAIN : 학습 데이터 행 개수
; N_THRESHOLD : 임계치 결정할 데이터 행 개수
; COLUMNS_LIST : 학습 시 사용할 데이터 열 리스트 (라벨 열 포함)
; LABEL_COLUMN : 라벨 열 이름
; APPLY_NORM : 데이터에 표준화 적용할 것인지
DATA_PATH = data_file/processed_steel_industry_data.csv
N_TRAIN = 15000
N_THRESHOLD = 1000
COLUMNS_LIST = Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,label
LABEL_COLUMN = label
APPLY_NORM = True

[model]
; WINDOW_SIZE : 윈도우 사이즈
; INPUT_SIZE : 입력값 사이즈
; OUTPUT_SIZE : 출력값 사이즈
; NUM_LAYERS : 레이어 개수
; HIDDEN_SIZE : 은닉층 사이즈
; LATENT_SIZE : (Auto-encoder) 잠재공간 사이즈
; BATCH_SIZE : 배치 사이즈
; IS_TRAIN : 학습 여부 (True=모델 학습, False=모델 학습X)
; MODEL_TYPE : 모델 유형 (predictor, reconstructor)
; MODEL_NAME : 모델 이름 (=추후 학습된 모델 경로) (lstm, lstm-auto-encoder)
; MODEL_DEVICE : 모델 cpu, gpu 이용
; NUM_EPOCHS : 에폭 수
WINDOW_SIZE = 16
INPUT_SIZE = 7
OUTPUT_SIZE = 7
NUM_LAYERS = 1
HIDDEN_SIZE = 32
LATENT_SIZE = 8
BATCH_SIZE = 32
IS_TRAIN = False
MODEL_TYPE = reconstructor
MODEL_NAME = lstm-auto-encoder
MODEL_DEVICE = cpu
NUM_EPOCHS = 10